python3 hiisitynnyri.py $1&
python3 hiisitynnyri.py $2&
python3 hiisitynnyri.py $3&
python3 hiisitynnyri.py $4&
python3 hiisitynnyri.py $5&
python3 hiisitynnyri.py $6&
python3 hiisitynnyri.py $7&
python3 hiisitynnyri.py $8&
python3 hiisitynnyri.py $9&
